// <auto-generated />
using System;
using HouseLens.Infrastructure.Persistence;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace HouseLens.Infrastructure.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20260627134711_AddSourceSiteToPriceHistory")]
    partial class AddSourceSiteToPriceHistory
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "10.0.9");

            modelBuilder.Entity("HouseLens.Domain.Entities.CrawlRun", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<int>("BigDropCount")
                        .HasColumnType("INTEGER");

                    b.Property<int>("DelistedCount")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime?>("FinishedAt")
                        .HasColumnType("TEXT");

                    b.Property<int>("NewCount")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("StartedAt")
                        .HasColumnType("TEXT");

                    b.Property<int>("Status")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("StartedAt");

                    b.ToTable("CrawlRuns");
                });

            modelBuilder.Entity("HouseLens.Domain.Entities.DistrictConfig", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("City")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("TEXT");

                    b.Property<string>("District")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("TEXT");

                    b.Property<bool>("IsEnabled")
                        .HasColumnType("INTEGER");

                    b.Property<decimal>("MaxTotalPrice")
                        .HasPrecision(12, 2)
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("City", "District")
                        .IsUnique();

                    b.ToTable("DistrictConfigs");
                });

            modelBuilder.Entity("HouseLens.Domain.Entities.Listing", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<string>("ImageUrl")
                        .HasMaxLength(1000)
                        .HasColumnType("TEXT");

                    b.Property<bool>("IsActive")
                        .HasColumnType("INTEGER");

                    b.Property<decimal>("LatestSourcePrice")
                        .HasPrecision(12, 2)
                        .HasColumnType("TEXT");

                    b.Property<DateTime?>("PostedDate")
                        .HasColumnType("TEXT");

                    b.Property<Guid>("PropertyId")
                        .HasColumnType("TEXT");

                    b.Property<string>("SourceListingKey")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.Property<int>("SourceSite")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("TEXT");

                    b.Property<string>("Url")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("PropertyId");

                    b.HasIndex("SourceSite", "SourceListingKey")
                        .IsUnique();

                    b.ToTable("Listings");
                });

            modelBuilder.Entity("HouseLens.Domain.Entities.NotificationLog", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<Guid>("CrawlRunId")
                        .HasColumnType("TEXT");

                    b.Property<string>("ErrorMessage")
                        .HasMaxLength(1000)
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("SentAt")
                        .HasColumnType("TEXT");

                    b.Property<bool>("Success")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Type")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("NotificationLogs");
                });

            modelBuilder.Entity("HouseLens.Domain.Entities.PriceHistoryEntry", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("CapturedAt")
                        .HasColumnType("TEXT");

                    b.Property<int>("ChangeFlag")
                        .HasColumnType("INTEGER");

                    b.Property<decimal?>("ChangePercent")
                        .HasPrecision(8, 4)
                        .HasColumnType("TEXT");

                    b.Property<Guid>("CrawlRunId")
                        .HasColumnType("TEXT");

                    b.Property<bool>("IsBigDrop")
                        .HasColumnType("INTEGER");

                    b.Property<Guid>("PropertyId")
                        .HasColumnType("TEXT");

                    b.Property<int>("SourceSite")
                        .HasColumnType("INTEGER");

                    b.Property<decimal>("TotalPrice")
                        .HasPrecision(12, 2)
                        .HasColumnType("TEXT");

                    b.Property<decimal?>("UnitPrice")
                        .HasPrecision(12, 2)
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("CrawlRunId");

                    b.HasIndex("PropertyId", "CrawlRunId", "SourceSite")
                        .IsUnique();

                    b.ToTable("PriceHistoryEntries");
                });

            modelBuilder.Entity("HouseLens.Domain.Entities.Property", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<string>("Address")
                        .HasMaxLength(200)
                        .HasColumnType("TEXT");

                    b.Property<int?>("AgeYears")
                        .HasColumnType("INTEGER");

                    b.Property<decimal>("AreaPing")
                        .HasPrecision(10, 2)
                        .HasColumnType("TEXT");

                    b.Property<string>("City")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("TEXT");

                    b.Property<decimal>("CurrentTotalPrice")
                        .HasPrecision(12, 2)
                        .HasColumnType("TEXT");

                    b.Property<decimal?>("CurrentUnitPrice")
                        .HasPrecision(12, 2)
                        .HasColumnType("TEXT");

                    b.Property<string>("District")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("FirstSeenAt")
                        .HasColumnType("TEXT");

                    b.Property<string>("Floor")
                        .HasMaxLength(20)
                        .HasColumnType("TEXT");

                    b.Property<bool>("HasParking")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("IsNew")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("LastSeenAt")
                        .HasColumnType("TEXT");

                    b.Property<Guid?>("MergedIntoPropertyId")
                        .HasColumnType("TEXT");

                    b.Property<int>("MissingCount")
                        .HasColumnType("INTEGER");

                    b.Property<decimal?>("Score")
                        .HasPrecision(5, 4)
                        .HasColumnType("TEXT");

                    b.Property<int>("Status")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("Status");

                    b.HasIndex("District", "Status");

                    b.ToTable("Properties");
                });

            modelBuilder.Entity("HouseLens.Domain.Entities.PropertyScore", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<decimal?>("AgeScore")
                        .HasPrecision(5, 4)
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("CalculatedAt")
                        .HasColumnType("TEXT");

                    b.Property<Guid>("CrawlRunId")
                        .HasColumnType("TEXT");

                    b.Property<decimal?>("LocationScore")
                        .HasPrecision(5, 4)
                        .HasColumnType("TEXT");

                    b.Property<decimal?>("ParkingScore")
                        .HasPrecision(5, 4)
                        .HasColumnType("TEXT");

                    b.Property<Guid>("PropertyId")
                        .HasColumnType("TEXT");

                    b.Property<decimal>("Score")
                        .HasPrecision(5, 4)
                        .HasColumnType("TEXT");

                    b.Property<decimal?>("UnitPriceScore")
                        .HasPrecision(5, 4)
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("PropertyId");

                    b.ToTable("PropertyScores");
                });

            modelBuilder.Entity("HouseLens.Domain.Entities.ScoringConfig", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<decimal>("BigDropAmount")
                        .HasPrecision(12, 2)
                        .HasColumnType("TEXT");

                    b.Property<decimal>("BigDropPercent")
                        .HasPrecision(5, 4)
                        .HasColumnType("TEXT");

                    b.Property<decimal>("WeightAge")
                        .HasPrecision(5, 4)
                        .HasColumnType("TEXT");

                    b.Property<decimal>("WeightLocation")
                        .HasPrecision(5, 4)
                        .HasColumnType("TEXT");

                    b.Property<decimal>("WeightParking")
                        .HasPrecision(5, 4)
                        .HasColumnType("TEXT");

                    b.Property<decimal>("WeightUnitPrice")
                        .HasPrecision(5, 4)
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("ScoringConfigs");
                });

            modelBuilder.Entity("HouseLens.Domain.Entities.SourceRunResult", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<Guid>("CrawlRunId")
                        .HasColumnType("TEXT");

                    b.Property<string>("ErrorMessage")
                        .HasMaxLength(1000)
                        .HasColumnType("TEXT");

                    b.Property<int>("FetchedCount")
                        .HasColumnType("INTEGER");

                    b.Property<int>("SourceSite")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("Success")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("CrawlRunId");

                    b.ToTable("SourceRunResults");
                });

            modelBuilder.Entity("HouseLens.Domain.Entities.TrackingCriteria", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Districts")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<decimal>("MaxTotalPrice")
                        .HasPrecision(12, 2)
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("TrackingCriteria");
                });

            modelBuilder.Entity("HouseLens.Domain.Entities.Listing", b =>
                {
                    b.HasOne("HouseLens.Domain.Entities.Property", "Property")
                        .WithMany("Listings")
                        .HasForeignKey("PropertyId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Property");
                });

            modelBuilder.Entity("HouseLens.Domain.Entities.PriceHistoryEntry", b =>
                {
                    b.HasOne("HouseLens.Domain.Entities.CrawlRun", "CrawlRun")
                        .WithMany("PriceHistoryEntries")
                        .HasForeignKey("CrawlRunId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("HouseLens.Domain.Entities.Property", "Property")
                        .WithMany("PriceHistory")
                        .HasForeignKey("PropertyId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("CrawlRun");

                    b.Navigation("Property");
                });

            modelBuilder.Entity("HouseLens.Domain.Entities.PropertyScore", b =>
                {
                    b.HasOne("HouseLens.Domain.Entities.Property", "Property")
                        .WithMany("Scores")
                        .HasForeignKey("PropertyId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Property");
                });

            modelBuilder.Entity("HouseLens.Domain.Entities.SourceRunResult", b =>
                {
                    b.HasOne("HouseLens.Domain.Entities.CrawlRun", "CrawlRun")
                        .WithMany("SourceResults")
                        .HasForeignKey("CrawlRunId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("CrawlRun");
                });

            modelBuilder.Entity("HouseLens.Domain.Entities.CrawlRun", b =>
                {
                    b.Navigation("PriceHistoryEntries");

                    b.Navigation("SourceResults");
                });

            modelBuilder.Entity("HouseLens.Domain.Entities.Property", b =>
                {
                    b.Navigation("Listings");

                    b.Navigation("PriceHistory");

                    b.Navigation("Scores");
                });
#pragma warning restore 612, 618
        }
    }
}
